### ISSUE TITLE
Regular players cant do coloured warp sign

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-welcomewarpsigns#10]
When normal player, which do not have additional permissions for colouring signs make [WELCOME]
it looks like
"&a[WELCOME]" or "&c[WELCOME]" < Its not colourd. Its just text

**Comment by tastybento** [comment]
Which plugin is preventing coloring signs? In vanilla Spigot there is no blocking of this kind.

**Comment by TheWranger** [comment]
@Kryniowesegryderiusz Was this issue ever fixed in CMI or is this something we will have to work around?

**Comment by Kryniowesegryderiusz** [comment]
It has to be worked around
