### ISSUE TITLE
Permissions for more warp signs

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/addon-welcomewarpsigns#18]
**Is your feature request related to a problem? Please describe.**
Server owners do not currently have any way to have dynamic warp sign limits for islands. We can also increase things like island protection range, island team size, and other things with permissions so I think that this fits.

**Describe the solution you'd like**
A permission that can be used to increase the limit of warp signs a player/team has. Like what we have for other things.

**Additional context**
Coupled with https://github.com/BentoBoxWorld/addon-welcomewarpsigns/issues/17,  I think this could be very useful for better restrictions on island warp signs (for per-team warp sign limits, the island owner's warp sign limit should be used for determining how many warp signs the island can have).

**Comment by tastybento** [comment]
The philosophy of warp signs is one per player. To enable more that one makes the warping system too complex.
