### ISSUE TITLE
Default warp sign limit

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/addon-welcomewarpsigns#19]
**Is your feature request related to a problem? Please describe.**
Server owners have no way to control how many warp signs people can have, by default.

**Describe the solution you'd like**
A configuration option that sets how many warp signs can have, by default. Should also be able to set limit to 0 so that server owners can perhaps give players access to warp signs after they complete some other task.

**Additional context**
Very good when combined with https://github.com/BentoBoxWorld/addon-welcomewarpsigns/issues/17 and https://github.com/BentoBoxWorld/addon-welcomewarpsigns/issues/18.

**Comment by tastybento** [comment]
Players can only have one sign. I’m confused.

**Comment by tastybento** [comment]
I just read the other request. Just one per player so this is moot.
