### ISSUE TITLE
Warps don't work in End & Nether

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/addon-welcomewarpsigns#21]
#### Describe the bug
Players are not able to place warps in End/Nether unless their **warplevelrestriction** is set to 0.
Even when you succeed placing it, you are unable to actually warp to it.

#### Steps to reproduce the behavior
1. **Players cannot set warps in nether/end if:**
`warplevelrestriction: >0` (Any number greater than zero) 
- It's due to the warp-addon not looking at the level of island in overworld, but the nether/end itself. Though, this is a problem of Levels addon also, because it does not supports Nether/End level calculation and therefore it's always '0'? (Might be a feature, will transfer it to Level section if required)
See: http://prntscr.com/mrzh8r (Restriction is 10 at the moment of capturing the screenshot)

2. **Players cannot warp to it with /is warp <nick>**
We bypassed the previous problem with:
`warplevelrestriction: 0`
- The warp is placed, the line becomes green, but players aren't able to warp to it with command.
- Output of **/is warp** <nick>: http://prntscr.com/mrzdom
#### Expected behavior
Be able to both set and warp to the warp-sign.
#### Server

 - OS: **Windows 10**
 - Java version: **Version 8; Update 191**

#### Plugins

```
[19:55:59 INFO]: Plugins (2): BentoBox, IslandBorder
```

##### BentoBox and Addons

```
[19:55:38 INFO]: Running SPIGOT 1.13.2.
[19:55:38 INFO]: BentoBox version: 1.4.0-SNAPSHOT
[19:55:38 INFO]: Loaded Game Worlds:
[19:55:38 INFO]: skyblock (skyblock)
[19:55:38 INFO]: Loaded Addons:
[19:55:38 INFO]: Biomes 0.5.0-SNAPSHOT
[19:55:38 INFO]: BSkyBlock 1.3.0
[19:55:38 INFO]: Challenges 0.6.0
[19:55:38 INFO]: Level 1.2.2-SNAPSHOT
[19:55:38 INFO]: SerbCraftAddon 2.0
[19:55:38 INFO]: WelcomeWarps 1.2-SNAPSHOT
```

##### Configuration

 - Database: **YAML** 

### Additional context
- **Alternative until End/Nether is not supported:**
Make welcomewarpsign addon look at the level of island in overworld, but 2nd case from above still needs to be solved for them to be able to warp to it.

**Comment by BONNe** [comment]
Please, update to Biomes 0.4.2 as 0.5.0-SNAPSHOT is outdated.

**Comment by wellnesscookie** [comment]
Will do @BONNe , thanks for the info! This one is on localhost, but good to know!

**Comment by tastybento** [comment]
Okay, fixed. Thanks for the report.
