### ISSUE TITLE
Please help warp sign

### ISSUE THREAD

**Issue by Krixiz** [BentoBoxWorld/addon-welcomewarpsigns#26]
**Description**
There is error in console and player can't  create welcome warp sign

![unnamed](https://user-images.githubusercontent.com/50483551/57745091-f7ebc680-76f5-11e9-9c5d-33060e871c57.jpg)
(I'm sorry I don't know hot copy on console)

**Comment by Poslovitch** [comment]
You are using a 1.14-related version while being on 1.13.2.
