### ISSUE TITLE
High load time on 1.14

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/addon-welcomewarpsigns#27]
**Description**

On 1.14.2, when you do /is warps, the server freezes for about 5 seconds and then, the GUI appears.
It happens even if you do it several times in a row (so the sign text are cached I guess?)

**Server Information:**

 - Database being used (YAML, JSON, MySQL, MongoDB): YAML

**Comment by tastybento** [comment]
can you take some timings and paste the URL here? I'd like to see what's taking so long.
Is your config default or did you select heads instead of signs?

**Comment by YellowZaki** [comment]
I have signs.
Here is the timings (I've disabled all the plugins, only BentoBox running):
https://timings.aikar.co/?id=b3e75fd223f742f6820cc5236b26a90b

**Comment by tastybento** [comment]
This should be fixed now.
