### ISSUE TITLE
Translation placeholder [text]

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/addon-welcomewarpsigns#28]
**Description**
When a player executes the command `/is warps` the following locale text lines are displayed:
`Place a warp sign with [WELCOME] on the top`
config.yml
```
# Text that player must put on sign to make it a warp sign
# Not case sensitive!
welcomeLine: '[Warp]'
```
The text line should have been: `Place a warp sign with [WARP] on the top`
**Steps to reproduce the behavior:**
1. Make a default server with every option default exept `welcomeLine: '[Warp]'`
2. Restart server to effect change
3. execute `/is warps`
4. See that the [TEXT] is hard coded and not replaced by the `welcomeLine`

**Expected behavior**
The text line should have been: `Place a warp sign with [WARP] on the top`

**Server Information:**
Paper 1.13.2
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: [Linux]
 - Java Version: [openjdk-8]
 - BentoBox version: [1.6.0-SNAPSHOT-b1207]
 - Addons:
Biomes 1.5.2.1-SNAPSHOT-b123 (ENABLED)
BSkyBlock 1.5.3-SNAPSHOT (ENABLED)
Challenges 0.8.0-SNAPSHOT-278 (ENABLED)
Level 1.5.1-SNAPSHOT (ENABLED)
Limits 0.2.3-SNAPSHOT (ENABLED)
MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
WelcomeWarps 1.5.1-SNAPSHOT (ENABLED)

**Comment by tastybento** [comment]
Thanks!
