### ISSUE TITLE
Warps are delete

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/addon-welcomewarpsigns#29]
**Description**
Sometimes, all warps are delete and all players need to make them again :(

**Steps to reproduce the behavior:**
Play and one day, all warps don't exist.

**Versions:**
BentoBox version: 1.6.0-SNPASHOT-b1203
Biomes : 1.5.2.1-SNAPSHOT-b123
BSkyblock: 1.5.0
Challenges: 0.8.0-SNAPSHOT-#278
Level: 1.5.0
WelcomeWarps: 1.5.0

**Comment by tastybento** [comment]
What database are you using? Also, do you have any logs from when this happened? They will be in the logs folder.

**Comment by Typheonn** [comment]
I have no log when it happens and i use database with YAML

**Comment by tastybento** [comment]
I recommend moving to JSON. You can switch by setting your database to YAML2JSON in BentoBox's config.yml.
Next time, if it happens, share a log of the console. Without logs, I cannot fix. Thanks!

**Comment by Typheonn** [comment]
Ok, i will do that. But i don't have any risk to lose datas if i do that ?

**Comment by tastybento** [comment]
There's no risk in moving from YAML to JSON. We are depreciating YAML so I recommend it.
Of course, always take backups. The process is set database name to be YAML2JSON. Then start server and then in the console do **bbox migrate**. Then again to confirm.

**Comment by tastybento** [comment]
No further comments. closing.
