### ISSUE TITLE
Problem with creating signs

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/addon-welcomewarpsigns#8]
When I make [WELCOME] sign it does not make warp. There aren't errors in console.

Paper(327) 1.13.1-R0.1-SNAPSHOT

BSkyBlock 0.1
BentoBox-WelcomeWarps  0.1
BentoBox version 0.9.0-alpha2

**Comment by Poslovitch** [comment]
I can reproduce this bug. Nothing happens, whatever the "welcomeLine" is set to in the config file.

**Comment by tastybento** [comment]
I cannot duplicate, sorry. This is my setup:

>bentobox version
[21:42:48 INFO]: Loaded Game Worlds
[21:42:48 INFO]: AcidIsland
[21:42:48 INFO]: BSkyBlock
[21:42:48 INFO]: Loaded Add-Ons
[21:42:48 INFO]: AcidIsland 0.3.0-SNAPSHOT
[21:42:48 INFO]: BSkyBlock 0.3.0-SNAPSHOT
[21:42:48 INFO]: BentoBox-Challenges 0.0.3-SNAPSHOT
[21:42:48 INFO]: BentoBox-WelcomeWarps 0.0.3-SNAPSHOT
[21:42:48 INFO]: BentoBox-InvSwitcher 0.0.1-SNAPSHOT
[21:42:48 INFO]: BentoBox-Level 0.0.2-SNAPSHOT

Maybe we need to update the binaries.

**Comment by Kryniowesegryderiusz** [comment]
```
05.10 15:12:08 [Server] INFO Loaded Game Worlds
05.10 15:12:08 [Server] INFO SkyBlock
05.10 15:12:08 [Server] INFO Loaded Add-Ons
05.10 15:12:08 [Server] INFO BSkyBlock 0.1
05.10 15:12:08 [Server] INFO BentoBox-WelcomeWarps 0.1
05.10 15:12:08 [Server] INFO BentoBox-Level 0.1
05.10 15:12:08 [Server] INFO BentoBox-Challenges 0.1
```

**Comment by Kryniowesegryderiusz** [comment]
`05.10 17:00:47 [Server] INFO Loaded Game Worlds
05.10 17:00:47 [Server] INFO SkyBlock
05.10 17:00:47 [Server] INFO Loaded Add-Ons
05.10 17:00:47 [Server] INFO BSkyBlock 0.3.0-SNAPSHOT
05.10 17:00:47 [Server] INFO BentoBox-Level 0.1
05.10 17:00:47 [Server] INFO BentoBox-Challenges 0.0.3-SNAPSHOT
05.10 17:00:47 [Server] INFO BentoBox-WelcomeWarps 0.0.3-SNAPSHOT
`
Still not working :/
Could it be problem with world name, which is not default?

**Comment by Poslovitch** [comment]
Oh, I didn't think about that. Tasty, my world name is not the default one as well.

**Comment by tastybento** [comment]
Okay, I found the problem. Yes, it was because I was not getting the world correctly from BentoBox. I was using get world by friendly name (which is also different I expect in your configs). Instead I use the add-on.getWorld() method, which does not care about names.
